name: HelloWorldCLI
options: 
  bundleIdPrefix: com.example.olesu
targets:
  HelloWorldCLI:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    settings:
      GENERATE_INFOPLIST_FILE: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

schemes:
  HelloWorldCLI:
    build:
      targets:
        HelloWorldCLI: [run, test, profile, analyze]
        